
IF OBJECT_ID('tempdb..#results') IS NOT NULL DROP TABLE #results;

declare @estDelDate as Date = DATEADD (week , -1 , GETDATE() );

SELECT
	PROHDR.AJPRO#	AS Pro
	, PROHDR.AJSCD	AS CustomerID
	, PROHDR.AJDID	AS DispatchCode
	, PROHDR.AJTPCS	AS Pieces
	, PROHDR.AJTWGT	AS [Weight]
	, PROHDR.AJSNM	AS Origin
	, PROHDR.AJSAD1	AS OriginAddress
	, PROHDR.AJSCTY	AS OriginCity
	, PROHDR.AJSST	AS OriginState
	, PROHDR.AJSZIP	AS OriginZIP
	, PROHDR.AJCNM	AS Consignee
	, PROHDR.AJCAD1	AS ConsigneeAddress
	, PROHDR.AJCCTY	AS ConsigneeCity
	, PROHDR.AJCST	AS ConsigneeState
	, PROHDR.AJCZIP	AS ConsigneeZIP
    , CASE WHEN	ISNULL(MFSTHDR.BAMFST, 0) <> 0
        THEN   	LTRIM(RTRIM(CAST(MFSTHDR.BAMFST AS VARCHAR(25))))
        ELSE	NULL
	  END AS Manifest
	, LTRIM(RTRIM(CAST(MFSTHDR.BATRKR AS VARCHAR(25)))) AS Tractor
	, CASE WHEN	ISNULL(LTRIM(RTRIM(CAST(PROHDR.AJBLNO AS VARCHAR(25)))), '') <> ''
        THEN   	LTRIM(RTRIM(CAST(PROHDR.AJBLNO AS VARCHAR(25))))
        ELSE	NULL
      END AS BOL
	, CASE WHEN	ISNULL(LTRIM(RTRIM(CAST(PROHDR.AJPONO AS VARCHAR(25)))), '') <> ''
        THEN   	LTRIM(RTRIM(CAST(PROHDR.AJPONO AS VARCHAR(25))))
        ELSE	NULL
      END AS PONumber
	, PUTRAN.DLPUNO AS Pickup#
	, CAST(CAST(APPT.BSDATE AS VARCHAR(10)) AS DATE) AS ApptDate
	, CAST(CAST(PROSTA.ALDATE AS VARCHAR(10)) AS DATE) AS EstDeliveryDate
	, CASE WHEN APPT.BSDLDT <> 0
        THEN CAST(CAST(APPT.BSDLDT AS VARCHAR(10)) AS DATE)
        ELSE NULL
    END AS DeliveredDate
into #results
FROM [PROHDR]  PROHDR
	INNER JOIN  [PROSTA]  PROSTA  on PROSTA.ALPRO	= PROHDR.AJPRO#		AND PROSTA.ALCO		= PROHDR.AJCO#
	LEFT JOIN   [MFSTPRO] MFSTPRO on MFSTPRO.BCPRO	= PROHDR.AJPRO#		AND MFSTPRO.BCCO#	= PROHDR.AJCO#
	LEFT JOIN   [MFSTHDR] MFSTHDR on MFSTHDR.BAMFST	= MFSTPRO.BCMFST	AND MFSTHDR.BACO#	= MFSTPRO.BCCO#
	LEFT  JOIN   [APPT]    APPT    on APPT.BSPRO		= PROHDR.AJPRO#		AND APPT.BSCONO		= PROHDR.AJCO#
	LEFT  JOIN   [PUTRAN]  PUTRAN  on PUTRAN.DLPRO	= PROHDR.AJPRO#
where	CAST(CAST(PROSTA.ALDATE AS VARCHAR(10)) AS DATE) >= @estDelDate
GROUP BY
	PROHDR.AJPRO#
	, PROHDR.AJSCD
	, PROHDR.AJDID
	, PROHDR.AJTPCS
	, PROHDR.AJTWGT
	, PROHDR.AJSNM
	, PROHDR.AJSAD1
	, PROHDR.AJSCTY
	, PROHDR.AJSST
	, PROHDR.AJSZIP
	, PROHDR.AJCNM
	, PROHDR.AJCAD1
	, PROHDR.AJCCTY
	, PROHDR.AJCST
	, PROHDR.AJCZIP
	, MFSTHDR.BAMFST
	, LTRIM(RTRIM(CAST(MFSTHDR.BATRKR AS VARCHAR(25))))
	, LTRIM(RTRIM(CAST(PROHDR.AJBLNO AS VARCHAR(25))))
	, LTRIM(RTRIM(CAST(PROHDR.AJPONO AS VARCHAR(25))))
	, PUTRAN.DLPUNO
	, CAST(CAST(APPT.BSDATE AS VARCHAR(10)) AS DATE)
	, CAST(CAST(PROSTA.ALDATE AS VARCHAR(10)) AS DATE)
	, APPT.BSDLDT;



--delete from #results where ISNULL(LTRIM(RTRIM(CAST(Tractor AS VARCHAR(25)))), '') = '';

select *
from #results
where pro = 361649064
order by Tractor, Pro, EstDeliveryDate;
